
import java.awt.Color;
import java.awt.Component;
import java.awt.FlowLayout;
import java.awt.List;
import java.sql.SQLException;
import java.util.Hashtable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import sun.swing.table.DefaultTableCellHeaderRenderer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Abdullah_PC
 */
public class Alta extends javax.swing.JFrame {
database db;
double CemMax,acMin;
boolean flagupdate=false;
int ID_formula;
Hashtable<Integer, GetEHE> store = new Hashtable<Integer, GetEHE>();
Hashtable<Integer,List> MaxMinGrupos=new Hashtable<>();

    /**
     * Creates new form Alta
     */
    public Alta() {
        initComponents();
        db=new database(1, "HM");
        DefaultComboBoxModel mod = new DefaultComboBoxModel(db.getAmbiente1().getItems());
        CompoAmbiente1.setModel(mod);
        BottonAddAmb3.setVisible(false);
        CompoAmbiente2.setVisible(false);
        CompoAmbiente3.setVisible(false);
        sacaFormulas("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CompoEHE = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        CompoResistencia = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CompoConsistencia = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        SpinnerTamanomax = new javax.swing.JSpinner();
        CompoAmbiente1 = new javax.swing.JComboBox<>();
        BottonAddAmb2 = new javax.swing.JButton();
        CompoAmbiente2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        CompoAmbiente3 = new javax.swing.JComboBox<>();
        BottonAddAmb3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListGrupo = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListFormula = new javax.swing.JList<>();
        ButtonAlta = new javax.swing.JButton();
        TextCem = new javax.swing.JTextField();
        Textac = new javax.swing.JTextField();
        TextAgua = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        SaveData = new javax.swing.JButton();
        ComboGrupo = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableGrupo = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        ListGrupovalid = new javax.swing.JList<>();
        LCem0 = new javax.swing.JLabel();
        LCem1 = new javax.swing.JLabel();
        LCem2 = new javax.swing.JLabel();
        LCem3 = new javax.swing.JLabel();
        LCem4 = new javax.swing.JLabel();
        LCem5 = new javax.swing.JLabel();
        LCem6 = new javax.swing.JLabel();
        LCem7 = new javax.swing.JLabel();
        LCem8 = new javax.swing.JLabel();
        LCem9 = new javax.swing.JLabel();
        LCem10 = new javax.swing.JLabel();
        LCem11 = new javax.swing.JLabel();
        LCem12 = new javax.swing.JLabel();
        LCem13 = new javax.swing.JLabel();
        LCem14 = new javax.swing.JLabel();
        LCem15 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ListCem = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        Lista_c = new javax.swing.JList<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        TextCemEdit = new javax.swing.JTextField();
        Texta_cEdit = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        TextGrupoUpdate = new javax.swing.JTextField();
        LMaxCem1 = new javax.swing.JLabel();
        LMinCem1 = new javax.swing.JLabel();
        LMaxCem = new javax.swing.JLabel();
        LMaxa_c1 = new javax.swing.JLabel();
        LMinCem = new javax.swing.JLabel();
        LMaxa_c = new javax.swing.JLabel();
        LMina_C = new javax.swing.JLabel();
        LMina_C1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CompoEHE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HM", "HA", "HP" }));
        CompoEHE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompoEHEActionPerformed(evt);
            }
        });
        getContentPane().add(CompoEHE, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 82, -1));

        jLabel1.setText("indicativoEHE08");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        CompoResistencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "20", "25", "30", "35", "40", "45", "50" }));
        getContentPane().add(CompoResistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 85, -1));

        jLabel2.setText("Resistencia");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 70, -1));

        jLabel3.setText("consistencia");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        CompoConsistencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "P", "B", "F", "L" }));
        getContentPane().add(CompoConsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 58, -1));

        jLabel4.setText("Tamano Max");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        SpinnerTamanomax.setMaximumSize(new java.awt.Dimension(0, 32767));
        SpinnerTamanomax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SpinnerTamanomaxMouseClicked(evt);
            }
        });
        getContentPane().add(SpinnerTamanomax, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 70, 25));

        CompoAmbiente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompoAmbiente1ActionPerformed(evt);
            }
        });
        getContentPane().add(CompoAmbiente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 80, -1));

        BottonAddAmb2.setText("+");
        BottonAddAmb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottonAddAmb2ActionPerformed(evt);
            }
        });
        getContentPane().add(BottonAddAmb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 40, -1));

        getContentPane().add(CompoAmbiente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 80, -1));

        jLabel7.setText("Ambiente");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 50, -1));

        getContentPane().add(CompoAmbiente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, 80, -1));

        BottonAddAmb3.setText("+");
        BottonAddAmb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottonAddAmb3ActionPerformed(evt);
            }
        });
        getContentPane().add(BottonAddAmb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 40, -1));

        jScrollPane1.setViewportView(ListGrupo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 50, 200));

        jScrollPane2.setViewportView(ListFormula);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 150, 200));

        ButtonAlta.setText("Alta");
        ButtonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAltaActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 80, -1));
        getContentPane().add(TextCem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 60, -1));

        Textac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextacMouseClicked(evt);
            }
        });
        Textac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextacActionPerformed(evt);
            }
        });
        getContentPane().add(Textac, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 60, -1));

        TextAgua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextAguaMouseClicked(evt);
            }
        });
        TextAgua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextAguaActionPerformed(evt);
            }
        });
        getContentPane().add(TextAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 60, -1));

        jLabel8.setText("Cem");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel9.setText("a/c");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabel10.setText("Agua");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        SaveData.setText("Salvar");
        SaveData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveDataActionPerformed(evt);
            }
        });
        getContentPane().add(SaveData, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 550, -1, -1));

        ComboGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboGrupoActionPerformed(evt);
            }
        });
        getContentPane().add(ComboGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 150, -1));

        TableGrupo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableGrupo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableGrupoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TableGrupoMouseEntered(evt);
            }
        });
        jScrollPane3.setViewportView(TableGrupo);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, 140));

        jScrollPane4.setViewportView(ListGrupovalid);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 90, 200));

        LCem0.setBackground(new java.awt.Color(255, 255, 255));
        LCem0.setText("jLabel5");
        LCem0.setOpaque(true);
        getContentPane().add(LCem0, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 40, -1));

        LCem1.setBackground(new java.awt.Color(255, 255, 255));
        LCem1.setText("jLabel5");
        LCem1.setOpaque(true);
        getContentPane().add(LCem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 40, -1));

        LCem2.setBackground(new java.awt.Color(255, 255, 255));
        LCem2.setText("jLabel6");
        LCem2.setOpaque(true);
        getContentPane().add(LCem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 40, -1));

        LCem3.setBackground(new java.awt.Color(255, 255, 255));
        LCem3.setText("jLabel11");
        LCem3.setOpaque(true);
        getContentPane().add(LCem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 40, -1));

        LCem4.setBackground(new java.awt.Color(255, 255, 255));
        LCem4.setText("jLabel12");
        LCem4.setOpaque(true);
        getContentPane().add(LCem4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 40, -1));

        LCem5.setBackground(new java.awt.Color(255, 255, 255));
        LCem5.setText("jLabel13");
        LCem5.setOpaque(true);
        getContentPane().add(LCem5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 40, -1));

        LCem6.setBackground(new java.awt.Color(255, 255, 255));
        LCem6.setText("jLabel14");
        LCem6.setOpaque(true);
        getContentPane().add(LCem6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 40, -1));

        LCem7.setBackground(new java.awt.Color(255, 255, 255));
        LCem7.setText("jLabel15");
        LCem7.setOpaque(true);
        getContentPane().add(LCem7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 40, -1));

        LCem8.setBackground(new java.awt.Color(255, 255, 255));
        LCem8.setText("jLabel5");
        LCem8.setOpaque(true);
        getContentPane().add(LCem8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 40, -1));

        LCem9.setBackground(new java.awt.Color(255, 255, 255));
        LCem9.setText("jLabel5");
        LCem9.setOpaque(true);
        getContentPane().add(LCem9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 40, -1));

        LCem10.setBackground(new java.awt.Color(255, 255, 255));
        LCem10.setText("jLabel6");
        LCem10.setOpaque(true);
        getContentPane().add(LCem10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 40, -1));

        LCem11.setBackground(new java.awt.Color(255, 255, 255));
        LCem11.setText("jLabel11");
        LCem11.setOpaque(true);
        getContentPane().add(LCem11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 40, -1));

        LCem12.setBackground(new java.awt.Color(255, 255, 255));
        LCem12.setText("jLabel12");
        LCem12.setOpaque(true);
        getContentPane().add(LCem12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 40, -1));

        LCem13.setBackground(new java.awt.Color(255, 255, 255));
        LCem13.setText("jLabel13");
        LCem13.setOpaque(true);
        getContentPane().add(LCem13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 40, -1));

        LCem14.setBackground(new java.awt.Color(255, 255, 255));
        LCem14.setText("jLabel14");
        LCem14.setOpaque(true);
        getContentPane().add(LCem14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 40, -1));

        LCem15.setBackground(new java.awt.Color(255, 255, 255));
        LCem15.setText("jLabel15");
        LCem15.setOpaque(true);
        getContentPane().add(LCem15, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 40, -1));

        jScrollPane5.setViewportView(ListCem);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 90, 200));

        jScrollPane6.setViewportView(Lista_c);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 80, 200));

        jLabel13.setText("Grupo");
        jLabel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel14.setText("Formula");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        jLabel15.setText("Cem ");
        jLabel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        jLabel16.setText("Valid a/c");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 60, -1));

        TextCemEdit.setText("0");
        TextCemEdit.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                TextCemEditInputMethodTextChanged(evt);
            }
        });
        TextCemEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCemEditActionPerformed(evt);
            }
        });
        getContentPane().add(TextCemEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 550, 120, -1));

        Texta_cEdit.setText("0");
        getContentPane().add(Texta_cEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 550, 110, -1));

        jLabel17.setText("a/c");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        jLabel18.setText("Grupos");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));

        jLabel19.setText("Valid Cem");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 60, -1));

        TextGrupoUpdate.setText("0");
        getContentPane().add(TextGrupoUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 100, -1));

        LMaxCem1.setText("Max Cem");
        getContentPane().add(LMaxCem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, -1, -1));

        LMinCem1.setText("Min Cem");
        getContentPane().add(LMinCem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 50, -1));

        LMaxCem.setText("jLabel5");
        LMaxCem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(LMaxCem, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 40, -1));

        LMaxa_c1.setText("Max a/c");
        getContentPane().add(LMaxa_c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 50, -1));

        LMinCem.setText("jLabel6");
        LMinCem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(LMinCem, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 40, -1));

        LMaxa_c.setText("jLabel11");
        LMaxa_c.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(LMaxa_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 410, 40, -1));

        LMina_C.setText("jLabel12");
        LMina_C.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(LMina_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, 40, -1));

        LMina_C1.setText("Min a/c");
        getContentPane().add(LMina_C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 440, 50, -1));

        jLabel11.setText("Cem");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 50, -1));

        jLabel12.setText("a/c");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, 50, -1));

        jLabel20.setText("Grupo");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, -1, -1));

        jLabel5.setBackground(new java.awt.Color(204, 204, 255));
        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Info de Grupo"));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 240, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CompoEHEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompoEHEActionPerformed
        // TODO add your handling code here:
        db=new database(1, CompoEHE.getSelectedItem().toString());
        DefaultComboBoxModel mod = new DefaultComboBoxModel(db.getAmbiente1().getItems());
        CompoAmbiente1.setModel(mod);
        
    }//GEN-LAST:event_CompoEHEActionPerformed

    private void SpinnerTamanomaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SpinnerTamanomaxMouseClicked
        // TODO add your handling code here:
        //jSpinner1.setValue(jSpinner1.getValue()+"a");
    }//GEN-LAST:event_SpinnerTamanomaxMouseClicked

    private void BottonAddAmb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottonAddAmb2ActionPerformed
        // TODO add your handling code here:
        db=new database(2, CompoEHE.getSelectedItem().toString());
        DefaultComboBoxModel mod = new DefaultComboBoxModel(db.getAmbiente2().getItems());
         CompoAmbiente2.setModel(mod);
         CompoAmbiente2.setVisible(true);
         BottonAddAmb3.setVisible(true);
    }//GEN-LAST:event_BottonAddAmb2ActionPerformed

    private void CompoAmbiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompoAmbiente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompoAmbiente1ActionPerformed

    private void BottonAddAmb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottonAddAmb3ActionPerformed
        // TODO add your handling code here:
        db=new database(2, CompoEHE.getSelectedItem().toString());
        DefaultComboBoxModel mod = new DefaultComboBoxModel(db.getAmbiente2().getItems());
         CompoAmbiente3.setModel(mod);
         CompoAmbiente3.setVisible(true);
        
    }//GEN-LAST:event_BottonAddAmb3ActionPerformed

    private void ButtonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAltaActionPerformed
        // TODO add your handling code here:
        List formula=new List();
        formula.add(CompoEHE.getSelectedItem().toString());
        formula.add(CompoAmbiente1.getSelectedItem().toString());
        if(CompoAmbiente2.isVisible())
        {
            formula.add(CompoAmbiente2.getSelectedItem().toString());
            if(CompoAmbiente3.isVisible())
                formula.add(CompoAmbiente3.getSelectedItem().toString());
        }
        
         database db=new database(formula);
         if(Double.parseDouble(TextCem.getText())<db.getCemMax()||Double.parseDouble(Textac.getText())>db.getAcmin())
         {
             JOptionPane.showMessageDialog(null, "Error!!!! EL Cem Max ="+db.getCemMax()+" ,Y EL Min a/c = "+db.getAcmin());
         }else{
              BottonAddAmb3.setVisible(false);
              CompoAmbiente2.setVisible(false);
              CompoAmbiente3.setVisible(false);
              TextAgua.setText(Math.round(Double.parseDouble(TextCem.getText())*Double.parseDouble(Textac.getText()))+"");
             
         
              db.SaveDate(formula, Integer.parseInt(CompoResistencia.getSelectedItem().toString()), CompoConsistencia.getSelectedItem().toString(), Integer.parseInt(SpinnerTamanomax.getValue().toString()), Double.parseDouble(TextCem.getText()), Double.parseDouble(Textac.getText()), Double.parseDouble(TextAgua.getText()), CompoResistencia.getSelectedIndex()+1,db.getCemMax(),db.getAcmin());
              
              
           
           System.out.println(Integer.parseInt(SpinnerTamanomax.getValue().toString()));
         }
         
         database d=new database();
        try {
                 d.GetAll("");
                store =d.getStore();
                 setDataToLists(store);
            } catch (SQLException ex) {
                Logger.getLogger(Alta.class.getName()).log(Level.SEVERE, null, ex);
            } 
         sacaFormulas("");
        
    }//GEN-LAST:event_ButtonAltaActionPerformed

    private void TextacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextacMouseClicked
        // TODO add your handling code here:
        Textac.setEnabled(true);
        TextAgua.setEnabled(false);
        
    }//GEN-LAST:event_TextacMouseClicked

    private void TextAguaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextAguaMouseClicked
        // TODO add your handling code here:
        Textac.setEnabled(false);
        TextAgua.setEnabled(true); 
    }//GEN-LAST:event_TextAguaMouseClicked

    private void TextacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextacActionPerformed

    private void TextAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextAguaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextAguaActionPerformed

    
    
    private void SaveDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveDataActionPerformed
        // TODO add your handling code here:
        database db=new database();
        double cem=Double.parseDouble(TextCemEdit.getText()),ac=Double.parseDouble(Texta_cEdit.getText());
        double agua=cem*ac;
        int grupo=Integer.parseInt(TextGrupoUpdate.getText());
        if(cem<CemMax||ac>acMin)
         JOptionPane.showMessageDialog(null, "Error!!!! EL Cem Max ="+store.get(ID_formula).getCmmax()+" ,Y EL Min a/c = "+store.get(ID_formula).getAcmin());
        else{
                db.UpdateDate(cem,ac , agua,grupo ,ID_formula);
                 TextCemEdit.setText("0");
        Texta_cEdit.setText("0");
        TextGrupoUpdate.setText("0");
        sacaFormulas("");
                }   
       
        
        
    }//GEN-LAST:event_SaveDataActionPerformed
 
    private void ComboGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboGrupoActionPerformed
        // TODO add your handling code here:
       DefaultTableModel model =new DefaultTableModel();
            TableGrupo.setModel(model);
            
            
            model.addColumn("Formula");
            model.addColumn("Cem");
            model.addColumn("a/c");
            model.addColumn("Valid Cem");
            model.addColumn("Valid a/c");
            model.addColumn("ID_formula");
            model.addColumn("Grupo");
            model.addColumn("Max Cem");
             model.addColumn("Min a/c");
             
        for(int i=0;i<store.size();i++){
            if(store.get(i).getGrupo()==ComboGrupo.getSelectedIndex()){
                // System.out.println(store.get(i).isValidcm()+"  "+store.get(i).isValidac());
                 Object o[]={store.get(i).gettodo(),store.get(i).getCm(),store.get(i).geta_c(),store.get(i).isValidcm(),store.get(i).isValidac(),store.get(i).getID_formula(),store.get(i).getGrupo(),store.get(i).getCmmax(),store.get(i).getAcmin()};
              
                 model.addRow(o);
                
                 
            }
           
        }
        TableColorCell cell=new TableColorCell();
                TableGrupo.setDefaultRenderer(Object.class, cell);
            LMaxCem.setText(MaxMinGrupos.get(ComboGrupo.getSelectedIndex()).getItem(0));
            LMinCem.setText(MaxMinGrupos.get(ComboGrupo.getSelectedIndex()).getItem(1));
            LMaxa_c.setText(MaxMinGrupos.get(ComboGrupo.getSelectedIndex()).getItem(2));
            LMina_C.setText(MaxMinGrupos.get(ComboGrupo.getSelectedIndex()).getItem(3));
    }//GEN-LAST:event_ComboGrupoActionPerformed

    private void TableGrupoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableGrupoMouseClicked
        // TODO add your handling code here:
       
       TextCemEdit.setText(TableGrupo.getValueAt(TableGrupo.getSelectedRow(),1).toString());
       Texta_cEdit.setText(TableGrupo.getValueAt(TableGrupo.getSelectedRow(),2).toString());
       ID_formula=Integer.parseInt(TableGrupo.getValueAt(TableGrupo.getSelectedRow(), 5).toString());
       TextGrupoUpdate.setText(TableGrupo.getValueAt(TableGrupo.getSelectedRow(), 6).toString());
       CemMax=Double.parseDouble(TableGrupo.getValueAt(TableGrupo.getSelectedRow(),7).toString());
       acMin=Double.parseDouble(TableGrupo.getValueAt(TableGrupo.getSelectedRow(),8).toString());
       
    }//GEN-LAST:event_TableGrupoMouseClicked

    private void TextCemEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCemEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCemEditActionPerformed

    private void TextCemEditInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_TextCemEditInputMethodTextChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_TextCemEditInputMethodTextChanged

    private void TableGrupoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableGrupoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_TableGrupoMouseEntered

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
         sacaFormulas("SELECT Formulas.*, Formulas.grupo\n" +
"FROM Formulas\n" +
"ORDER BY Formulas.grupo;");
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
sacaFormulas("SELECT Formulas.*, Formulas.grupo\n" +
"FROM Formulas\n" +
"ORDER BY Formulas.cem;");
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BottonAddAmb2;
    private javax.swing.JButton BottonAddAmb3;
    private javax.swing.JButton ButtonAlta;
    private javax.swing.JComboBox<String> ComboGrupo;
    private javax.swing.JComboBox<String> CompoAmbiente1;
    private javax.swing.JComboBox<String> CompoAmbiente2;
    private javax.swing.JComboBox<String> CompoAmbiente3;
    private javax.swing.JComboBox<String> CompoConsistencia;
    private javax.swing.JComboBox<String> CompoEHE;
    private javax.swing.JComboBox<String> CompoResistencia;
    private javax.swing.JLabel LCem0;
    private javax.swing.JLabel LCem1;
    private javax.swing.JLabel LCem10;
    private javax.swing.JLabel LCem11;
    private javax.swing.JLabel LCem12;
    private javax.swing.JLabel LCem13;
    private javax.swing.JLabel LCem14;
    private javax.swing.JLabel LCem15;
    private javax.swing.JLabel LCem2;
    private javax.swing.JLabel LCem3;
    private javax.swing.JLabel LCem4;
    private javax.swing.JLabel LCem5;
    private javax.swing.JLabel LCem6;
    private javax.swing.JLabel LCem7;
    private javax.swing.JLabel LCem8;
    private javax.swing.JLabel LCem9;
    private javax.swing.JLabel LMaxCem;
    private javax.swing.JLabel LMaxCem1;
    private javax.swing.JLabel LMaxa_c;
    private javax.swing.JLabel LMaxa_c1;
    private javax.swing.JLabel LMinCem;
    private javax.swing.JLabel LMinCem1;
    private javax.swing.JLabel LMina_C;
    private javax.swing.JLabel LMina_C1;
    private javax.swing.JList<String> ListCem;
    private javax.swing.JList<String> ListFormula;
    private javax.swing.JList<String> ListGrupo;
    private javax.swing.JList<String> ListGrupovalid;
    private javax.swing.JList<String> Lista_c;
    private javax.swing.JButton SaveData;
    private javax.swing.JSpinner SpinnerTamanomax;
    private javax.swing.JTable TableGrupo;
    private javax.swing.JTextField TextAgua;
    private javax.swing.JTextField TextCem;
    private javax.swing.JTextField TextCemEdit;
    private javax.swing.JTextField TextGrupoUpdate;
    private javax.swing.JTextField Texta_cEdit;
    private javax.swing.JTextField Textac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    // End of variables declaration//GEN-END:variables
    
     
    private void setDataToLists(Hashtable<Integer, GetEHE> store) {
       DefaultListModel modGrupo=new DefaultListModel(); 
       DefaultListModel modFormula=new DefaultListModel();
       DefaultListModel modCem=new DefaultListModel(); 
       DefaultListModel moda_c=new DefaultListModel();
       //To change body of generated methods, choose Tools | Templates.
         ListGrupo.setModel(modGrupo);
         ListFormula.setModel(modFormula);
         ListCem.setModel(modCem);
         Lista_c.setModel(moda_c);
         GetEHE ee=new GetEHE();
         for(int i=0;i<store.size();i++){
             ee=store.get(i);
              modGrupo.addElement(ee.getGrupo());
             modFormula.addElement(ee.gettodo());
             modCem.addElement(ee.cm);
              moda_c.addElement(ee.a_c);
                     
         }
    }

    private void checkGrupoIfOkey( Hashtable<Integer, List> MaxMinGrupos) {
        DefaultComboBoxModel mod=new  DefaultComboBoxModel();
        DefaultListModel modList=new  DefaultListModel();
        ComboGrupo.setModel(mod);
        ListGrupovalid.setModel(modList);
        boolean []max=new boolean[MaxMinGrupos.size()];
      boolean []min=new boolean[MaxMinGrupos.size()];
      JLabel ja=new JLabel("asdasd");
      
      
    
      for(int i=0;i<max.length;i++){
          mod.addElement("Grupo "+i);
            modList.addElement("Grupo "+i);
         
          
          
          
      max[i]=true;
      min[i]=true;
      }
      
      for(int i=0;i<MaxMinGrupos.size();i++){
          for(int j=0;j<store.size();j++){
             GetEHE e=store.get(j);
             double Maxcem=Double.parseDouble(MaxMinGrupos.get(i).getItem(0));
             double Mincem=Double.parseDouble(MaxMinGrupos.get(i).getItem(1));
             double Maxac=Double.parseDouble(MaxMinGrupos.get(i).getItem(2));
             double Minac=Double.parseDouble(MaxMinGrupos.get(i).getItem(3));
             
             if(e.getGrupo()==i){
                 System.out.println(i);
                 if(e.getCm()>Mincem+30||e.getCm()<Maxcem-30){
                 max[i]=false;
                 e.setValidcm(false);
             }else{
                     e.setValidcm(true);
                 }
              if(e.geta_c()>Minac+0.004||e.geta_c()<Maxac-0.004){
                   min[i]=false;
                    e.setValidac(false);
                 }else{
                  e.setValidac(true);
              }
              store.put(j, e);
             }
            
             
             }
         
      }
             setGrupoVal(max,min);
             
            
          }
    
    public void setGrupoVal(boolean max[],boolean min[]){
                    
        for(int i=0;i<max.length;i++)
        switch(i){
                     case 0:
                         if(max[i]){
                             LCem0.setText("SI");
                             LCem0.setBackground(Color.green);
                          }
                         else
                         {
                           LCem0.setText("NO");
                             LCem0.setBackground(Color.RED);  
                         }
                         if(min[i]){
                             LCem8.setText("SI");
                             LCem8.setBackground(Color.green);
                          }
                         else
                         {
                           LCem8.setText("NO");
                             LCem8.setBackground(Color.RED);  
                         }
                             
                         
                         break;
                     case 1:
                          if(max[i]){
                             LCem1.setText("SI");
                             LCem1.setBackground(Color.green);
                          }
                         else
                         {
                           LCem1.setText("NO");
                             LCem1.setBackground(Color.RED);  
                         }
                         if(min[i]){
                             LCem9.setText("SI");
                             LCem9.setBackground(Color.green);
                          }
                         else
                         {
                           LCem9.setText("NO");
                             LCem9.setBackground(Color.RED);  
                         }
                         break;
                     case 2:
                          if(max[i]){
                             LCem2.setText("SI");
                             LCem2.setBackground(Color.green);
                          }
                         else
                         {
                           LCem2.setText("NO");
                             LCem2.setBackground(Color.RED);  
                         }
                         if(min[i]){
                             LCem10.setText("SI");
                             LCem10.setBackground(Color.green);
                          }
                         else
                         {
                           LCem10.setText("NO");
                             LCem10.setBackground(Color.RED);  
                         }
                         break;
                     case 3:
                         
                         if(max[i]){
                             LCem3.setText("SI");
                             LCem3.setBackground(Color.green);
                          }
                         else
                         {
                           LCem3.setText("NO");
                             LCem3.setBackground(Color.RED);  
                         }
                         if(min[i]){
                             LCem11.setText("SI");
                             LCem11.setBackground(Color.green);
                          }
                         else
                         {
                           LCem11.setText("NO");
                             LCem11.setBackground(Color.RED);  
                         }
                         break;
                     case 4:
                         if(max[i]){
                             LCem4.setText("SI");
                             LCem4.setBackground(Color.green);
                          }
                         else
                         {
                           LCem4.setText("NO");
                             LCem4.setBackground(Color.RED);  
                         }
                         if(min[i]){
                             LCem12.setText("SI");
                             LCem12.setBackground(Color.green);
                          }
                         else
                         {
                           LCem12.setText("NO");
                             LCem12.setBackground(Color.RED);  
                         }
                         
                         break;
                     case 5:
                         if(max[i]){
                             LCem5.setText("SI");
                             LCem5.setBackground(Color.green);
                          }
                         else
                         {
                           LCem5.setText("NO");
                             LCem5.setBackground(Color.RED);  
                         }
                         if(min[i]){
                             LCem13.setText("SI");
                             LCem13.setBackground(Color.green);
                          }
                         else
                         {
                           LCem13.setText("NO");
                             LCem13.setBackground(Color.RED);  
                         }
                         
                         break;
                     case 6:
                         if(max[i]){
                             LCem6.setText("SI");
                             LCem6.setBackground(Color.green);
                          }
                         else
                         {
                           LCem6.setText("NO");
                             LCem6.setBackground(Color.RED);  
                         }
                         if(min[i]){
                             LCem14.setText("SI");
                             LCem14.setBackground(Color.green);
                          }
                         else
                         {
                           LCem14.setText("NO");
                             LCem14.setBackground(Color.RED);  
                         }
                         
                         break;
                     case 7:
                         if(max[i]){
                             LCem7.setText("SI");
                             LCem7.setBackground(Color.green);
                          }
                         else
                         {
                           LCem7.setText("NO");
                             LCem7.setBackground(Color.RED);  
                         }
                         if(min[i]){
                             LCem15.setText("SI");
                             LCem15.setBackground(Color.green);
                          }
                         else
                         {
                           LCem15.setText("NO");
                             LCem15.setBackground(Color.RED);  
                         }
                         
                         break;
                     
                 }
    }
    
    private void sacaFormulas(String Sql){
        database d=new database();
        try {
                 d.GetAll(Sql);
                store =d.getStore();
                 setDataToLists(store);
            } catch (SQLException ex) {
                Logger.getLogger(Alta.class.getName()).log(Level.SEVERE, null, ex);
            }
        try {
        // TODO add your handling code here:
         d=new database();
       MaxMinGrupos= d.getMax_Min_Grupo();
       
    } catch (SQLException ex) {
        Logger.getLogger(Alta.class.getName()).log(Level.SEVERE, null, ex);
    } 
        
        checkGrupoIfOkey(MaxMinGrupos);
    }
      }
    
              
    

    


