
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStreamReader;
import java.util.Arrays;
import java.util.Hashtable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Abdullah_PC
 */
public class AltaDeFormulas extends javax.swing.JFrame {
          String []indicativoEHE08;
          String []resistencia;
          String []consistencia;
          String []ambiente;
          String []ambientenuevo;
          double [][]values;
          boolean flagAmbenuevo=false;
           Hashtable<Integer, GetEHE> store = new Hashtable<Integer, GetEHE>();
           int count=0;
          boolean flagisnotvis;
           
    /**
     * Creates new form AltaDeFormulas
     */
    public AltaDeFormulas() throws FileNotFoundException {
        initComponents();
        GetEHE();
        combofill();
         flagisnotvis=false;
        jLabel6.setVisible(false);
        ambiente2combo.setVisible(false);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TamanoMax = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ambiente1Combo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        bottonAlta = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ambiente2combo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cm = new javax.swing.JTextField();
        agua = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jLabel12 = new javax.swing.JLabel();
        ca = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TableNoApro = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        Valid = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        NoValid = new javax.swing.JList<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane8 = new javax.swing.JScrollPane();
        TableApro = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 76, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 85, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 58, -1));

        jLabel1.setText("indicativoEHE08");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setText("resistencia");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 70, -1));

        jLabel3.setText("consistencia");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 10, -1, -1));

        jLabel4.setText("Tamano Max");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        TamanoMax.setText("0");
        TamanoMax.setToolTipText("");
        getContentPane().add(TamanoMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 61, -1));

        jLabel5.setText("ambiente");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        ambiente1Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(ambiente1Combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 141, 128, -1));

        bottonAlta.setBackground(new java.awt.Color(51, 255, 51));
        bottonAlta.setText("Alta");
        bottonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonAltaActionPerformed(evt);
            }
        });
        getContentPane().add(bottonAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 102, -1));

        jButton2.setText("+");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        ambiente2combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(ambiente2combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, -1));

        jLabel6.setText("ambiente");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 56, -1));

        jScrollPane2.setViewportView(jList2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 141, 68, -1));

        jScrollPane3.setViewportView(jList3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 141, 79, -1));

        jLabel7.setText("Las Formulas");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 116, -1, -1));

        jLabel8.setText("CM ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 118, -1, -1));

        cm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmActionPerformed(evt);
            }
        });
        getContentPane().add(cm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, 76, -1));
        getContentPane().add(agua, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 85, 67, -1));

        jLabel10.setText("CM");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 64, -1, -1));

        jLabel11.setText("Agua");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        jScrollPane4.setViewportView(jList4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 141, 32, -1));

        jLabel12.setText("Grupo");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 116, -1, -1));
        getContentPane().add(ca, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 85, 63, -1));

        jLabel13.setText("A/C");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 64, -1, -1));

        TableNoApro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Gruop1", "Grupo2", "Grupo3", "Grupo4", "Gruop5", "Gruop6", "Gruop7"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(TableNoApro);
        if (TableNoApro.getColumnModel().getColumnCount() > 0) {
            TableNoApro.getColumnModel().getColumn(0).setResizable(false);
            TableNoApro.getColumnModel().getColumn(0).setHeaderValue("Gruop1");
            TableNoApro.getColumnModel().getColumn(1).setResizable(false);
            TableNoApro.getColumnModel().getColumn(1).setHeaderValue("Grupo2");
            TableNoApro.getColumnModel().getColumn(2).setHeaderValue("Grupo3");
            TableNoApro.getColumnModel().getColumn(3).setHeaderValue("Grupo4");
            TableNoApro.getColumnModel().getColumn(4).setHeaderValue("Gruop5");
            TableNoApro.getColumnModel().getColumn(5).setHeaderValue("Gruop6");
            TableNoApro.getColumnModel().getColumn(6).setHeaderValue("Gruop7");
        }

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 579, 180));

        Valid.setBackground(new java.awt.Color(153, 255, 153));
        jScrollPane6.setViewportView(Valid);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 141, 111, -1));

        NoValid.setBackground(new java.awt.Color(255, 51, 51));
        jScrollPane7.setViewportView(NoValid);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 141, 111, -1));

        jLabel14.setText("Valid");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 121, -1, -1));

        jLabel15.setText("No Valid");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 121, -1, -1));

        jLabel16.setText("Agua");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 64, -1, -1));

        jCheckBox1.setText("ambiente nuevo");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        TableApro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Gruop1", "Grupo2", "Grupo3", "Grupo4", "Gruop5", "Gruop6", "Gruop7"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(TableApro);
        if (TableApro.getColumnModel().getColumnCount() > 0) {
            TableApro.getColumnModel().getColumn(0).setResizable(false);
            TableApro.getColumnModel().getColumn(0).setHeaderValue("Gruop1");
            TableApro.getColumnModel().getColumn(1).setResizable(false);
            TableApro.getColumnModel().getColumn(1).setHeaderValue("Grupo2");
            TableApro.getColumnModel().getColumn(2).setHeaderValue("Grupo3");
            TableApro.getColumnModel().getColumn(3).setHeaderValue("Grupo4");
            TableApro.getColumnModel().getColumn(4).setHeaderValue("Gruop5");
            TableApro.getColumnModel().getColumn(5).setHeaderValue("Gruop6");
            TableApro.getColumnModel().getColumn(6).setHeaderValue("Gruop7");
        }

        getContentPane().add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 579, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    DefaultListModel mod=new DefaultListModel();
    DefaultListModel cmmax=new DefaultListModel();
    DefaultListModel cmmin=new DefaultListModel();
   DefaultListModel Grupo=new DefaultListModel();
   DefaultListModel valid=new DefaultListModel();
  DefaultListModel novalid=new DefaultListModel();
    private void bottonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonAltaActionPerformed
       String EHE;
       GetEHE EHE08=new GetEHE();
       double cmm,caa;
   
       System.out.println(flagisnotvis);
        
            EHE08.setIndicativoEHE08(indicativoEHE08[jComboBox1.getSelectedIndex()]);
            EHE08.setResistencia(resistencia[jComboBox2.getSelectedIndex()]);
            EHE08.setConsistencia(consistencia[jComboBox3.getSelectedIndex()]);
            EHE08.setTamanomax(TamanoMax.getText().toString());
           if(flagisnotvis==false){
               if(flagAmbenuevo){
                   EHE08.setAmbiente(ambiente[ambiente1Combo.getSelectedIndex()]);  
             cmm=values[jComboBox1.getSelectedIndex()+9][ambiente1Combo.getSelectedIndex()];
             caa=values[jComboBox1.getSelectedIndex()][ambiente1Combo.getSelectedIndex()];
               }else{
                   EHE08.setAmbiente(ambiente[ambiente1Combo.getSelectedIndex()]);  
             cmm=values[jComboBox1.getSelectedIndex()+3][ambiente1Combo.getSelectedIndex()];
             caa=values[jComboBox1.getSelectedIndex()][ambiente1Combo.getSelectedIndex()];
               }
             
           }
            
           else{
               EHE08.setAmbiente(ambiente[ambiente1Combo.getSelectedIndex()]+"+"+ambiente[ambiente2combo.getSelectedIndex()]); 
               if(values[jComboBox1.getSelectedIndex()+3][ambiente1Combo.getSelectedIndex()]>values[jComboBox1.getSelectedIndex()+3][ambiente2combo.getSelectedIndex()])
               { 
                   cmm=values[jComboBox1.getSelectedIndex()+3][ambiente1Combo.getSelectedIndex()];
                   caa=values[jComboBox1.getSelectedIndex()][ambiente1Combo.getSelectedIndex()];
               }else{
                   cmm=values[jComboBox1.getSelectedIndex()+3][ambiente2combo.getSelectedIndex()];
                   caa=values[jComboBox1.getSelectedIndex()][ambiente2combo.getSelectedIndex()];
               }
                   }
           
           EHE=EHE08.gettodo();
            
            
        EHE08.setCmmax(cmm);
        EHE08.setCmmin(caa);
        EHE08.setGrupo(jComboBox2.getSelectedIndex()+1);
        EHE08.setFirmado(true);
        EHE08.setCorreo("abdullah@yahoo.com");
        EHE08.setFechadevalid(16000005L);
        EHE08.setIdPlanta("Planta1");
        
        
        EHE08.setCm( Double.valueOf(cm.getText()));
        EHE08.setAgua( Double.valueOf(agua.getText()));
        double temp=Math.round(EHE08.getAgua()/EHE08.getCm()*100);
        EHE08.setCa(temp/100);
        
        //
        ca.setText(EHE08.getCa()+"");
        
        EHE08.valid(EHE08.getCmmax(), EHE08.getCmmin(), EHE08.getCm(),EHE08.getCa());
        
        
        store.put(count, EHE08);
        jList1.setModel(mod);
        jList2.setModel(cmmax);
        jList3.setModel(cmmin);
        jList4.setModel(Grupo);
        Valid.setModel(valid);
        NoValid.setModel(novalid);
        
        
        mod.addElement(EHE);
        cmmax.addElement(EHE08.getCmmax());
        cmmin.addElement(EHE08.getCmmin());
        Grupo.addElement(EHE08.getGrupo());
        
        
        String v="======";
        String nov="======";
        if(EHE08.isValidcm()&&EHE08.isValidac())
            v=EHE08.getCm()+"   "+EHE08.getCa();
        
        else if(!EHE08.isValidcm()&&!EHE08.isValidac())
            nov=EHE08.getCm()+"   "+EHE08.getCa();
        else if(EHE08.isValidcm()&&!EHE08.isValidac())
        {
           v=EHE08.getCm()+"  =====";
           nov="====  "+EHE08.getCa();
        }
        else{
            nov=EHE08.getCm()+"=====  ";
           v="=====  "+EHE08.getCa(); 
        }
        valid.addElement(v);
        novalid.addElement(nov);
        flagisnotvis=false;
        jLabel6.setVisible(false);
        ambiente2combo.setVisible(false);
        // TODO add your handling co
        
        // TODO add your handling code here:
        new Grupos(store);
            count++;
    }//GEN-LAST:event_bottonAltaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jLabel6.setVisible(true);
        ambiente2combo.setVisible(true);
        flagisnotvis=true;
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected()){
            flagAmbenuevo=true;
            
        }else{
            flagAmbenuevo=false;
        }
        combofill();
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaDeFormulas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaDeFormulas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaDeFormulas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaDeFormulas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AltaDeFormulas().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(AltaDeFormulas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> NoValid;
    private javax.swing.JTable TableApro;
    private javax.swing.JTable TableNoApro;
    private javax.swing.JTextField TamanoMax;
    private javax.swing.JList<String> Valid;
    private javax.swing.JTextField agua;
    private javax.swing.JComboBox<String> ambiente1Combo;
    private javax.swing.JComboBox<String> ambiente2combo;
    private javax.swing.JButton bottonAlta;
    private javax.swing.JTextField ca;
    private javax.swing.JTextField cm;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    // End of variables declaration//GEN-END:variables

 void GetEHE() throws FileNotFoundException{
      
        String IdPlantaFileName = ".\\resources\\indicativoEHE08.txt";
        String s;
        String sb="";
        
         try
        {
              FileInputStream ip=new FileInputStream(IdPlantaFileName);
           //InputStream is = getClass().getClassLoader().getResourceAsStream(SQLFileName);
            BufferedReader reader = new BufferedReader(new InputStreamReader(ip)) ;
                while((s = reader.readLine()) != null)
                {
                    sb=sb+s;
                }
                
              String EHE08[]=sb.split("#");
              resistencia=EHE08[0].split(",");
              consistencia=EHE08[1].split(",");
              
              
             String  EHE081[]=EHE08[2].split("@");
             System.out.println(EHE081.length);
             String indicativoEHE088[]=EHE081[0].split(",");
             indicativoEHE08=indicativoEHE088;
             String ambiente1[]=EHE081[1].split(",");
             ambiente=ambiente1;
             ambientenuevo=EHE081[2].split(",");
             double values1[][]=new double[15][ambiente1.length];
                    for(int i=0;i<values1.length;i++)
                    {
                        values1[i]=Arrays.stream(EHE081[i+3].split(",")).mapToDouble(Double::parseDouble).toArray();
                                
                    }
                    
                   
                        
              for(int i=0;i<values1.length;i++){
                  for(int j=0;j<values1[i].length;j++)
                    {
                        if(i<3)
                        {
                            values1[i][j]=values1[i][j]/100;
                        }
                     
                    }
             
              }
              values=values1;
              for(int i=0;i<ambientenuevo.length;i++)
                  System.out.print(values[14][i]+" ");
                        
             
            }
          catch(Exception e)
        {
                e.printStackTrace();
        }
  
    }
  private void combofill(){
       jComboBox1.removeAllItems();
       ambiente1Combo.removeAllItems();
         ambiente2combo.removeAllItems();
       jComboBox2.removeAllItems();
       jComboBox3.removeAllItems();
       
       
        DefaultComboBoxModel mod = new DefaultComboBoxModel(indicativoEHE08);
           jComboBox1.setModel(mod);
         
         mod = new DefaultComboBoxModel(resistencia);
           jComboBox2.setModel(mod);
           
           mod = new DefaultComboBoxModel(consistencia);
           jComboBox3.setModel(mod);
           
           
    if(flagAmbenuevo){
         mod = new DefaultComboBoxModel(ambientenuevo);
           ambiente1Combo.setModel(mod);
        mod = new DefaultComboBoxModel(ambientenuevo);
           ambiente2combo.setModel(mod);
    }else{
      mod = new DefaultComboBoxModel(ambiente);
           ambiente1Combo.setModel(mod);
        mod = new DefaultComboBoxModel(ambiente);
           ambiente2combo.setModel(mod);   
    }
        
          
    }
}
