package com.eqa.formula.screen;




import com.eqa.formula.DataBase.GetEHE;
import com.eqa.formula.utilidades.TableColorCell;
import com.eqa.formula.DataBase.database;
import com.eqa.formula.utilidades.CreatePdfDocument;


import com.itextpdf.text.DocumentException;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;

import java.awt.List;
import java.awt.Toolkit;


import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;

import java.sql.SQLException;
import java.util.Date;
import java.util.Hashtable;
import java.util.logging.Level;
import java.util.logging.Logger;


import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

import javax.swing.JOptionPane;

import javax.swing.filechooser.FileNameExtensionFilter;

import javax.swing.table.DefaultTableModel;

import org.json.simple.parser.ParseException;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Abdullah_PC
 */
public class Alta extends javax.swing.JFrame {
    //Firebase
    
database db;
double CemMax,acMin;
boolean flagupdate=false;
int ID_formula;
Hashtable<Integer, GetEHE> store = new Hashtable<Integer, GetEHE>();
Hashtable<Integer,List> MaxMinGrupos=new Hashtable<>();
String path="",name;
Date fechadesde;
static String plantaID,plantaDes;



    /**
     * Creates new form Alta
     * @param PlantaID
     * @param PlantaDes
     */
    public Alta(String PlantaID,String PlantaDes) {
        
        initComponents();
        db=new database(1, "HM","");
        DefaultComboBoxModel mod = new DefaultComboBoxModel(db.getAmbiente1().getItems());
        CompoAmbiente1.setModel(mod);
        BottonAddAmb3.setVisible(false);
        CompoAmbiente2.setVisible(false);
        CompoAmbiente3.setVisible(false);
        BottonAddAmb4.setVisible(false);
        CompoAmbiente4.setVisible(false);
        sacaFormulas("");
        Alta.plantaID=PlantaID;
        Alta.plantaDes=PlantaDes;
     
        lableDesPlanta.setText(plantaDes);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CompoEHE = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        CompoResistencia = new javax.swing.JComboBox<>();
        LableResistencia = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CompoConsistencia = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        SpinnerTamanomax = new javax.swing.JSpinner();
        CompoAmbiente1 = new javax.swing.JComboBox<>();
        BottonAddAmb2 = new javax.swing.JButton();
        CompoAmbiente2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        CompoAmbiente3 = new javax.swing.JComboBox<>();
        BottonAddAmb3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListGrupo = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListFormula = new javax.swing.JList<>();
        ButtonAlta = new javax.swing.JButton();
        TextCem = new javax.swing.JTextField();
        Textac = new javax.swing.JTextField();
        TextAgua = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        SaveData = new javax.swing.JButton();
        ComboGrupo = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableGrupo = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        ListGrupovalid = new javax.swing.JList<>();
        LCem0 = new javax.swing.JLabel();
        LCem1 = new javax.swing.JLabel();
        LCem2 = new javax.swing.JLabel();
        LCem3 = new javax.swing.JLabel();
        LCem4 = new javax.swing.JLabel();
        LCem5 = new javax.swing.JLabel();
        LCem6 = new javax.swing.JLabel();
        LCem7 = new javax.swing.JLabel();
        LCem8 = new javax.swing.JLabel();
        LCem9 = new javax.swing.JLabel();
        LCem10 = new javax.swing.JLabel();
        LCem11 = new javax.swing.JLabel();
        LCem12 = new javax.swing.JLabel();
        LCem13 = new javax.swing.JLabel();
        LCem14 = new javax.swing.JLabel();
        LCem15 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ListCem = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        Lista_c = new javax.swing.JList<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        TextCemEdit = new javax.swing.JTextField();
        Texta_cEdit = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        TextGrupoUpdate = new javax.swing.JTextField();
        LMaxCem1 = new javax.swing.JLabel();
        LMinCem1 = new javax.swing.JLabel();
        LMaxCem = new javax.swing.JLabel();
        LMaxa_c1 = new javax.swing.JLabel();
        LMinCem = new javax.swing.JLabel();
        LMaxa_c = new javax.swing.JLabel();
        LMina_C = new javax.swing.JLabel();
        LMina_C1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ButtonDeletFormula = new javax.swing.JButton();
        Buttonfirmar = new javax.swing.JButton();
        BottonAddAmb4 = new javax.swing.JButton();
        CompoAmbiente4 = new javax.swing.JComboBox<>();
        bottonOuctar = new javax.swing.JButton();
        bottonAparecer = new javax.swing.JButton();
        ButtonFirma2 = new javax.swing.JButton();
        imageFirma = new javax.swing.JLabel();
        TextName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CheckBoxAmbienteNuevas = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        DateValid = new com.toedter.calendar.JDateChooser();
        jLabel22 = new javax.swing.JLabel();
        lableDesPlanta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CompoEHE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HM", "HA", "HP", "HL", "HNE" }));
        CompoEHE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompoEHEActionPerformed(evt);
            }
        });
        getContentPane().add(CompoEHE, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 82, -1));

        jLabel1.setText("indicativoEHE08");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        CompoResistencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "20", "25", "30", "35", "40", "45", "50" }));
        getContentPane().add(CompoResistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 85, -1));

        LableResistencia.setText("Resistencia");
        getContentPane().add(LableResistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 70, -1));

        jLabel3.setText("consistencia");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        CompoConsistencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "P", "B", "F", "L" }));
        getContentPane().add(CompoConsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 58, -1));

        jLabel4.setText("Tamano Max");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        SpinnerTamanomax.setMaximumSize(new java.awt.Dimension(0, 32767));
        SpinnerTamanomax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SpinnerTamanomaxMouseClicked(evt);
            }
        });
        getContentPane().add(SpinnerTamanomax, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 70, 25));

        CompoAmbiente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompoAmbiente1ActionPerformed(evt);
            }
        });
        getContentPane().add(CompoAmbiente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 80, -1));

        BottonAddAmb2.setText("+");
        BottonAddAmb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottonAddAmb2ActionPerformed(evt);
            }
        });
        getContentPane().add(BottonAddAmb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 40, -1));

        getContentPane().add(CompoAmbiente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 80, -1));

        jLabel7.setText("Ambiente");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 70, -1));

        CompoAmbiente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompoAmbiente3ActionPerformed(evt);
            }
        });
        getContentPane().add(CompoAmbiente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, 80, -1));

        BottonAddAmb3.setText("+");
        BottonAddAmb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottonAddAmb3ActionPerformed(evt);
            }
        });
        getContentPane().add(BottonAddAmb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 40, -1));

        ListGrupo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListGrupoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListGrupo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 50, 200));

        ListFormula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListFormulaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ListFormula);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 150, 200));

        ButtonAlta.setText("Alta");
        ButtonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAltaActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 80, 30));
        getContentPane().add(TextCem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 60, -1));

        Textac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextacMouseClicked(evt);
            }
        });
        Textac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextacActionPerformed(evt);
            }
        });
        getContentPane().add(Textac, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 60, -1));

        TextAgua.setEnabled(false);
        TextAgua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextAguaMouseClicked(evt);
            }
        });
        TextAgua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextAguaActionPerformed(evt);
            }
        });
        getContentPane().add(TextAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 60, -1));

        jLabel8.setText("Cem");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel9.setText("a/c");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabel10.setText("Agua");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        SaveData.setText("Salvar");
        SaveData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveDataActionPerformed(evt);
            }
        });
        getContentPane().add(SaveData, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, 70, -1));

        ComboGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboGrupoActionPerformed(evt);
            }
        });
        getContentPane().add(ComboGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 150, -1));

        TableGrupo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Formula", "Cem", "a/c", "Valid Cem", "Valid a/cl", "ID_formual", "Grupo", "Min Cem", "Max a/c"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableGrupo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableGrupoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TableGrupo);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 380, 500, 140));

        jScrollPane4.setViewportView(ListGrupovalid);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 90, 200));

        LCem0.setBackground(new java.awt.Color(255, 255, 255));
        LCem0.setOpaque(true);
        getContentPane().add(LCem0, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 40, -1));

        LCem1.setBackground(new java.awt.Color(255, 255, 255));
        LCem1.setOpaque(true);
        getContentPane().add(LCem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 40, -1));

        LCem2.setBackground(new java.awt.Color(255, 255, 255));
        LCem2.setOpaque(true);
        getContentPane().add(LCem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 40, -1));

        LCem3.setBackground(new java.awt.Color(255, 255, 255));
        LCem3.setOpaque(true);
        getContentPane().add(LCem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 40, -1));

        LCem4.setBackground(new java.awt.Color(255, 255, 255));
        LCem4.setOpaque(true);
        getContentPane().add(LCem4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 40, -1));

        LCem5.setBackground(new java.awt.Color(255, 255, 255));
        LCem5.setOpaque(true);
        getContentPane().add(LCem5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 40, -1));

        LCem6.setBackground(new java.awt.Color(255, 255, 255));
        LCem6.setOpaque(true);
        getContentPane().add(LCem6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 40, -1));

        LCem7.setBackground(new java.awt.Color(255, 255, 255));
        LCem7.setOpaque(true);
        getContentPane().add(LCem7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 40, -1));

        LCem8.setBackground(new java.awt.Color(255, 255, 255));
        LCem8.setOpaque(true);
        getContentPane().add(LCem8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 40, -1));

        LCem9.setBackground(new java.awt.Color(255, 255, 255));
        LCem9.setOpaque(true);
        getContentPane().add(LCem9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 40, -1));

        LCem10.setBackground(new java.awt.Color(255, 255, 255));
        LCem10.setOpaque(true);
        getContentPane().add(LCem10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 40, -1));

        LCem11.setBackground(new java.awt.Color(255, 255, 255));
        LCem11.setOpaque(true);
        getContentPane().add(LCem11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 40, -1));

        LCem12.setBackground(new java.awt.Color(255, 255, 255));
        LCem12.setOpaque(true);
        getContentPane().add(LCem12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 40, -1));

        LCem13.setBackground(new java.awt.Color(255, 255, 255));
        LCem13.setOpaque(true);
        getContentPane().add(LCem13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 40, -1));

        LCem14.setBackground(new java.awt.Color(255, 255, 255));
        LCem14.setOpaque(true);
        getContentPane().add(LCem14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 40, -1));

        LCem15.setBackground(new java.awt.Color(255, 255, 255));
        LCem15.setOpaque(true);
        getContentPane().add(LCem15, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 40, -1));

        ListCem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListCemMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(ListCem);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 90, 200));

        Lista_c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lista_cMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(Lista_c);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 80, 200));

        jLabel13.setText("Grupo");
        jLabel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel14.setText("Formula");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        jLabel15.setText("Cem ");
        jLabel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        jLabel16.setText("Valid a/c");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 60, -1));

        TextCemEdit.setText("0");
        TextCemEdit.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                TextCemEditInputMethodTextChanged(evt);
            }
        });
        TextCemEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCemEditActionPerformed(evt);
            }
        });
        getContentPane().add(TextCemEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 550, 120, -1));

        Texta_cEdit.setText("0");
        getContentPane().add(Texta_cEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 550, 110, -1));

        jLabel17.setText("a/c");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        jLabel18.setText("Grupos");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));

        jLabel19.setText("Valid Cem");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 60, -1));

        TextGrupoUpdate.setText("0");
        getContentPane().add(TextGrupoUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 100, -1));

        LMaxCem1.setText("Max Cem");
        getContentPane().add(LMaxCem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, -1, -1));

        LMinCem1.setText("Min Cem");
        getContentPane().add(LMinCem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 50, -1));

        LMaxCem.setText("jLabel5");
        LMaxCem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(LMaxCem, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 40, -1));

        LMaxa_c1.setText("Max a/c");
        getContentPane().add(LMaxa_c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 50, -1));

        LMinCem.setText("jLabel6");
        LMinCem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(LMinCem, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 40, -1));

        LMaxa_c.setText("jLabel11");
        LMaxa_c.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(LMaxa_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, 40, -1));

        LMina_C.setText("jLabel12");
        LMina_C.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(LMina_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 440, 40, -1));

        LMina_C1.setText("Min a/c");
        getContentPane().add(LMina_C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 50, -1));

        jLabel11.setText("Cem");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 50, -1));

        jLabel12.setText("a/c");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, 50, -1));

        jLabel20.setText("Grupo");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, -1, -1));

        jLabel5.setBackground(new java.awt.Color(204, 204, 255));
        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Info de Grupo"));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 240, 110));

        ButtonDeletFormula.setText("Eliminar");
        ButtonDeletFormula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeletFormulaActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonDeletFormula, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 560, -1, -1));

        Buttonfirmar.setText("Firmar");
        Buttonfirmar.setEnabled(false);
        Buttonfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(Buttonfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 380, 130, -1));

        BottonAddAmb4.setText("+");
        BottonAddAmb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottonAddAmb4ActionPerformed(evt);
            }
        });
        getContentPane().add(BottonAddAmb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 40, -1));

        getContentPane().add(CompoAmbiente4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 80, -1));

        bottonOuctar.setText("Oucltar");
        bottonOuctar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonOuctarActionPerformed(evt);
            }
        });
        getContentPane().add(bottonOuctar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 530, 80, -1));

        bottonAparecer.setText("Aparecer");
        bottonAparecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonAparecerActionPerformed(evt);
            }
        });
        getContentPane().add(bottonAparecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 560, -1, -1));

        ButtonFirma2.setText("Importar Firma");
        ButtonFirma2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFirma2ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonFirma2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 410, 130, -1));
        getContentPane().add(imageFirma, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 550, 130, 100));

        TextName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNameActionPerformed(evt);
            }
        });
        getContentPane().add(TextName, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 460, 130, 30));

        jLabel2.setText("Fecha");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 500, 130, -1));

        CheckBoxAmbienteNuevas.setText("Ambiente Nuevas");
        CheckBoxAmbienteNuevas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxAmbienteNuevasActionPerformed(evt);
            }
        });
        getContentPane().add(CheckBoxAmbienteNuevas, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 140, -1));

        jLabel6.setText("Nombre de Técnico");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 440, 120, -1));

        jButton1.setText("LogOut");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 620, -1, -1));

        DateValid.setToolTipText("");
        DateValid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                DateValidFocusLost(evt);
            }
        });
        getContentPane().add(DateValid, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 520, 130, 30));

        jLabel22.setText("Planta");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 360, 40, -1));

        lableDesPlanta.setText("jLabel24");
        getContentPane().add(lableDesPlanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 360, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CompoEHEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompoEHEActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel modRec=new DefaultComboBoxModel() ;
   
        db=new database(1, CompoEHE.getSelectedItem().toString(),"");
        DefaultComboBoxModel mod = new DefaultComboBoxModel(db.getAmbiente1().getItems());
        CompoAmbiente1.setModel(mod);
        
            if(CompoEHE.getSelectedIndex()==3){
            CompoResistencia.removeAllItems();
           CompoResistencia.setModel(modRec);
          modRec.addElement("100");
          modRec.addElement("150");
          modRec.addElement("170");
          LableResistencia.setText("Min Cem");
        }else if(CompoEHE.getSelectedIndex()==4){
            
        CompoResistencia.removeAllItems();
           CompoResistencia.setModel(modRec);
          modRec.addElement("15");
          modRec.addElement("17.5");
         
        }
        else{
           CompoResistencia.removeAllItems();
           CompoResistencia.setModel(modRec);
          modRec.addElement("20");
          modRec.addElement("25");
           modRec.addElement("30");
          modRec.addElement("35"); 
           modRec.addElement("40");
          modRec.addElement("45"); 
           modRec.addElement("50");
           LableResistencia.setText("Resistencia");
          
        }
        
    }//GEN-LAST:event_CompoEHEActionPerformed

    private void SpinnerTamanomaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SpinnerTamanomaxMouseClicked
        // TODO add your handling code here:
        //jSpinner1.setValue(jSpinner1.getValue()+"a");
    }//GEN-LAST:event_SpinnerTamanomaxMouseClicked

    private void BottonAddAmb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottonAddAmb2ActionPerformed
        // TODO add your handling code here:
        if(BottonAddAmb2.getText().equalsIgnoreCase("+")){
        db=new database(2, CompoEHE.getSelectedItem().toString(),"");
        DefaultComboBoxModel mod = new DefaultComboBoxModel(db.getAmbiente2().getItems());
         CompoAmbiente2.setModel(mod);
         CompoAmbiente2.setVisible(true);
         BottonAddAmb3.setVisible(true);
         BottonAddAmb2.setText("-");
        }
        else
        {
          CompoAmbiente2.setVisible(false);
         BottonAddAmb3.setVisible(false);
         CompoAmbiente3.setVisible(false);
         BottonAddAmb4.setVisible(false);
         CompoAmbiente4.setVisible(false);
         BottonAddAmb2.setText("+");  
         BottonAddAmb3.setText("+");  
          BottonAddAmb4.setText("+");
        }
    }//GEN-LAST:event_BottonAddAmb2ActionPerformed

    private void CompoAmbiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompoAmbiente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompoAmbiente1ActionPerformed

    private void BottonAddAmb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottonAddAmb3ActionPerformed
        // TODO add your handling code here:
        if(BottonAddAmb3.getText().equalsIgnoreCase("+")){
        db=new database(3, CompoEHE.getSelectedItem().toString(),"");
        DefaultComboBoxModel mod = new DefaultComboBoxModel(db.getAmbiente3().getItems());
         CompoAmbiente3.setModel(mod);
         CompoAmbiente3.setVisible(true);
         BottonAddAmb3.setText("-");
         BottonAddAmb4.setVisible(true);
        }else{
         CompoAmbiente3.setVisible(false);  
         BottonAddAmb3.setText("+");
         CompoAmbiente4.setVisible(false);  
         BottonAddAmb4.setText("+");
          BottonAddAmb4.setVisible(false);
        }
        
    }//GEN-LAST:event_BottonAddAmb3ActionPerformed

    private void ButtonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAltaActionPerformed
        // TODO add your handling code here:
        formulaAlta();
        
    }//GEN-LAST:event_ButtonAltaActionPerformed

    private void TextacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextacMouseClicked
        // TODO add your handling code here:
        Textac.setEnabled(true);
        TextAgua.setEnabled(false);
        
    }//GEN-LAST:event_TextacMouseClicked

    private void TextAguaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextAguaMouseClicked
        // TODO add your handling code here:
        Textac.setEnabled(false);
        TextAgua.setEnabled(true); 
    }//GEN-LAST:event_TextAguaMouseClicked

    private void TextacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextacActionPerformed

    private void TextAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextAguaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextAguaActionPerformed

    
    
    private void SaveDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveDataActionPerformed
        // TODO add your handling code here:
         int indexgrupo=ComboGrupo.getSelectedIndex();
        database db=new database();
        double cem=Double.parseDouble(TextCemEdit.getText()),ac=Double.parseDouble(Texta_cEdit.getText());
        double agua=cem*ac;
        int grupo=Integer.parseInt(TextGrupoUpdate.getText());
        if(cem<CemMax||ac>acMin && ComboGrupo.getSelectedIndex()>0)
         JOptionPane.showMessageDialog(null, "Error!!!! EL Cem Min ="+CemMax+" ,Y EL Max a/c = "+acMin);
        else{
                db.UpdateDate(cem,ac , agua,grupo ,ID_formula);
                 TextCemEdit.setText("0");
        Texta_cEdit.setText("0");
        TextGrupoUpdate.setText("0");
        sacaFormulas("");
        ComboGrupo.setSelectedIndex(indexgrupo);
         JOptionPane.showMessageDialog(null, "La Formula Ya esta salvada");
                }   
       
        
        
    }//GEN-LAST:event_SaveDataActionPerformed
 
    private void ComboGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboGrupoActionPerformed
        // TODO add your handling code here:
      
       DefaultTableModel model =new DefaultTableModel();
            TableGrupo.setModel(model);
            model.addColumn("Formula");
            model.addColumn("Cem");
            model.addColumn("a/c");
            model.addColumn("Valid Cem");
            model.addColumn("Valid a/c");
            model.addColumn("ID_formula");
            model.addColumn("Grupo");
            model.addColumn("Min Cem");
            model.addColumn("Max a/c");
            model.addColumn("Ouctar");
            
         
             
        for(int i=0;i<store.size();i++){
                
            if(store.get(i).getGrupo()==ComboGrupo.getSelectedIndex()){
                // System.out.println(store.get(i).isValidcm()+"  "+store.get(i).isValidac());
                 Object o[]={store.get(i).gettodo(),store.get(i).getCm(),store.get(i).geta_c(),store.get(i).isValidcm(),store.get(i).isValidac(),store.get(i).getID_formula(),store.get(i).getGrupo(),store.get(i).getCmmax(),store.get(i).getAcmin(),store.get(i).isOuctar()};
                 
                 model.addRow(o);
                
                 
            }
           
        }
           TableColorCell cell=new TableColorCell();
            TableGrupo.setDefaultRenderer(Object.class, cell);
            LMaxCem.setText(MaxMinGrupos.get(ComboGrupo.getSelectedIndex()).getItem(0));
            LMinCem.setText(MaxMinGrupos.get(ComboGrupo.getSelectedIndex()).getItem(1));
            LMaxa_c.setText(MaxMinGrupos.get(ComboGrupo.getSelectedIndex()).getItem(2));
            LMina_C.setText(MaxMinGrupos.get(ComboGrupo.getSelectedIndex()).getItem(3));
           
            
    }//GEN-LAST:event_ComboGrupoActionPerformed

    private void TableGrupoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableGrupoMouseClicked
        // TODO add your handling code here:
       
       TextCemEdit.setText(TableGrupo.getValueAt(TableGrupo.getSelectedRow(),1).toString());
       Texta_cEdit.setText(TableGrupo.getValueAt(TableGrupo.getSelectedRow(),2).toString());
       ID_formula=Integer.parseInt(TableGrupo.getValueAt(TableGrupo.getSelectedRow(), 5).toString());
       TextGrupoUpdate.setText(TableGrupo.getValueAt(TableGrupo.getSelectedRow(), 6).toString());
       CemMax=Double.parseDouble(TableGrupo.getValueAt(TableGrupo.getSelectedRow(),7).toString());
       acMin=Double.parseDouble(TableGrupo.getValueAt(TableGrupo.getSelectedRow(),8).toString());
       
    }//GEN-LAST:event_TableGrupoMouseClicked

    private void TextCemEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCemEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCemEditActionPerformed

    private void TextCemEditInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_TextCemEditInputMethodTextChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_TextCemEditInputMethodTextChanged

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
         sacaFormulas("SELECT Formulas.*, Formulas.grupo\n" +
"FROM Formulas\n" +
"ORDER BY Formulas.grupo;");
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
sacaFormulas("SELECT Formulas.*, Formulas.grupo\n" +
"FROM Formulas\n" +
"ORDER BY Formulas.cem;");
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseClicked

    private void ListGrupoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListGrupoMouseClicked
        // TODO add your handling code here:
        ListFormula.setSelectedIndex(ListGrupo.getSelectedIndex());
        ListCem.setSelectedIndex(ListGrupo.getSelectedIndex());
        Lista_c.setSelectedIndex(ListGrupo.getSelectedIndex());
    }//GEN-LAST:event_ListGrupoMouseClicked

    private void ListFormulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListFormulaMouseClicked
        // TODO add your handling code here:
        ListGrupo.setSelectedIndex(ListFormula.getSelectedIndex());
        ListCem.setSelectedIndex(ListFormula.getSelectedIndex());
        Lista_c.setSelectedIndex(ListFormula.getSelectedIndex());
    }//GEN-LAST:event_ListFormulaMouseClicked

    private void ListCemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListCemMouseClicked
        // TODO add your handling code here:
        ListGrupo.setSelectedIndex(ListCem.getSelectedIndex());
        ListFormula.setSelectedIndex(ListCem.getSelectedIndex());
        Lista_c.setSelectedIndex(ListCem.getSelectedIndex());
    }//GEN-LAST:event_ListCemMouseClicked

    private void Lista_cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lista_cMouseClicked
        // TODO add your handling code here:
         ListGrupo.setSelectedIndex(Lista_c.getSelectedIndex());
        ListFormula.setSelectedIndex(Lista_c.getSelectedIndex());
        ListCem.setSelectedIndex(Lista_c.getSelectedIndex());
    }//GEN-LAST:event_Lista_cMouseClicked

    private void ButtonDeletFormulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeletFormulaActionPerformed
 int indexgrupo=ComboGrupo.getSelectedIndex();
        
                // TODO add your handling code here:
        database db=new database();
    try {
        db.deleteformula(ID_formula);
        sacaFormulas("");
        ComboGrupo.setSelectedIndex(indexgrupo);
        JOptionPane.showMessageDialog(null, "La Formula Ya esta eliminada");
    } catch (SQLException ex) {
        Logger.getLogger(Alta.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    }//GEN-LAST:event_ButtonDeletFormulaActionPerformed

    private void ButtonfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonfirmarActionPerformed
        // TODO add your handling code here:
        if(DateValid.getDate()==null){
             JOptionPane.showMessageDialog(null, "Entre La fecha, por favor.");
             throw new UnsupportedOperationException("Entre La fecha, por favor."); 
        }
            
        try {
        // TODO add your handling code here:\
        name=TextName.getText();
        fechadesde=DateValid.getDate();
        database d=new database();
        store =d.GetAll("");
        
        
        new CreatePdfDocument(store,path,name,fechadesde,plantaDes,plantaID);
    } catch (FileNotFoundException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    } catch (DocumentException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IOException ex) {
        Logger.getLogger(Alta.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(Alta.class.getName()).log(Level.SEVERE, null, ex);
    }
        
        JOptionPane.showMessageDialog(null, "Ya han subido todos los formulas, se puede sacar el certificado firmado");
    }//GEN-LAST:event_ButtonfirmarActionPerformed

    private void BottonAddAmb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottonAddAmb4ActionPerformed
        // TODO add your handling code here:
          if(BottonAddAmb4.getText().equalsIgnoreCase("+")){
        db=new database(4, CompoEHE.getSelectedItem().toString(),CompoAmbiente3.getSelectedItem().toString());
        DefaultComboBoxModel mod = new DefaultComboBoxModel(db.getAmbiente4().getItems());
         CompoAmbiente4.setModel(mod);
         CompoAmbiente4.setVisible(true);
         BottonAddAmb4.setText("-");
        }else{
         CompoAmbiente4.setVisible(false);  
         BottonAddAmb4.setText("+");
        }
    }//GEN-LAST:event_BottonAddAmb4ActionPerformed

    private void CompoAmbiente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompoAmbiente3ActionPerformed
        // TODO add your handling code here:
         db=new database(4, CompoEHE.getSelectedItem().toString(),CompoAmbiente3.getSelectedItem().toString());
  DefaultComboBoxModel mod = new DefaultComboBoxModel(db.getAmbiente4().getItems());
   CompoAmbiente4.setModel(mod);
    }//GEN-LAST:event_CompoAmbiente3ActionPerformed

    private void bottonOuctarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonOuctarActionPerformed
        // TODO add your handling code here:
           int indexgrupo=ComboGrupo.getSelectedIndex();
          database db=new database();
          db.ocultadaformula(ID_formula,true);
          sacaFormulas("");
            ComboGrupo.setSelectedIndex(indexgrupo);
          JOptionPane.showMessageDialog(null, "La Formula Ya está ocultada");
 
          
    }//GEN-LAST:event_bottonOuctarActionPerformed

    private void bottonAparecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonAparecerActionPerformed

        // TODO add your handling code here:
        int indexgrupo=ComboGrupo.getSelectedIndex();
         database db=new database();
          db.ocultadaformula(ID_formula,false);
          sacaFormulas("");
          ComboGrupo.setSelectedIndex(indexgrupo); 
          JOptionPane.showMessageDialog(null, "La Formula Ya está Aparecada");
        
    }//GEN-LAST:event_bottonAparecerActionPerformed

    private void ButtonFirma2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFirma2ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser=new JFileChooser();
        chooser.addChoosableFileFilter(new FileNameExtensionFilter("Images", "jpg", "png", "gif", "bmp"));
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
         path=f.getAbsolutePath();
        
        Image im=Toolkit.getDefaultToolkit().createImage(path);
        im=im.getScaledInstance(imageFirma.getWidth(),imageFirma.getHeight(), Image.SCALE_DEFAULT);
        ImageIcon icon=new ImageIcon(im);
        imageFirma.setIcon(icon);
    }//GEN-LAST:event_ButtonFirma2ActionPerformed

    private void TextNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNameActionPerformed

    private void CheckBoxAmbienteNuevasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxAmbienteNuevasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxAmbienteNuevasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    try {
        new Login().setVisible(true);
    } catch (IOException ex) {
        Logger.getLogger(Alta.class.getName()).log(Level.SEVERE, null, ex);
    } catch (ParseException ex) {
        Logger.getLogger(Alta.class.getName()).log(Level.SEVERE, null, ex);
    }
;
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DateValidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DateValidFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_DateValidFocusLost

    
    
    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alta(plantaID,plantaDes).setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BottonAddAmb2;
    private javax.swing.JButton BottonAddAmb3;
    private javax.swing.JButton BottonAddAmb4;
    private javax.swing.JButton ButtonAlta;
    private javax.swing.JButton ButtonDeletFormula;
    private javax.swing.JButton ButtonFirma2;
    private javax.swing.JButton Buttonfirmar;
    private javax.swing.JCheckBox CheckBoxAmbienteNuevas;
    private javax.swing.JComboBox<String> ComboGrupo;
    private javax.swing.JComboBox<String> CompoAmbiente1;
    private javax.swing.JComboBox<String> CompoAmbiente2;
    private javax.swing.JComboBox<String> CompoAmbiente3;
    private javax.swing.JComboBox<String> CompoAmbiente4;
    private javax.swing.JComboBox<String> CompoConsistencia;
    private javax.swing.JComboBox<String> CompoEHE;
    private javax.swing.JComboBox<String> CompoResistencia;
    private com.toedter.calendar.JDateChooser DateValid;
    private javax.swing.JLabel LCem0;
    private javax.swing.JLabel LCem1;
    private javax.swing.JLabel LCem10;
    private javax.swing.JLabel LCem11;
    private javax.swing.JLabel LCem12;
    private javax.swing.JLabel LCem13;
    private javax.swing.JLabel LCem14;
    private javax.swing.JLabel LCem15;
    private javax.swing.JLabel LCem2;
    private javax.swing.JLabel LCem3;
    private javax.swing.JLabel LCem4;
    private javax.swing.JLabel LCem5;
    private javax.swing.JLabel LCem6;
    private javax.swing.JLabel LCem7;
    private javax.swing.JLabel LCem8;
    private javax.swing.JLabel LCem9;
    private javax.swing.JLabel LMaxCem;
    private javax.swing.JLabel LMaxCem1;
    private javax.swing.JLabel LMaxa_c;
    private javax.swing.JLabel LMaxa_c1;
    private javax.swing.JLabel LMinCem;
    private javax.swing.JLabel LMinCem1;
    private javax.swing.JLabel LMina_C;
    private javax.swing.JLabel LMina_C1;
    private javax.swing.JLabel LableResistencia;
    private javax.swing.JList<String> ListCem;
    private javax.swing.JList<String> ListFormula;
    private javax.swing.JList<String> ListGrupo;
    private javax.swing.JList<String> ListGrupovalid;
    private javax.swing.JList<String> Lista_c;
    private javax.swing.JButton SaveData;
    private javax.swing.JSpinner SpinnerTamanomax;
    private javax.swing.JTable TableGrupo;
    private javax.swing.JTextField TextAgua;
    private javax.swing.JTextField TextCem;
    private javax.swing.JTextField TextCemEdit;
    private javax.swing.JTextField TextGrupoUpdate;
    private javax.swing.JTextField TextName;
    private javax.swing.JTextField Texta_cEdit;
    private javax.swing.JTextField Textac;
    private javax.swing.JButton bottonAparecer;
    private javax.swing.JButton bottonOuctar;
    private javax.swing.JLabel imageFirma;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lableDesPlanta;
    // End of variables declaration//GEN-END:variables
    
     
    private void setDataToLists(Hashtable<Integer, GetEHE> store) {
       DefaultListModel modGrupo=new DefaultListModel(); 
       DefaultListModel modFormula=new DefaultListModel();
       DefaultListModel modCem=new DefaultListModel(); 
       DefaultListModel moda_c=new DefaultListModel();
       //To change body of generated methods, choose Tools | Templates.
         ListGrupo.setModel(modGrupo);
         ListFormula.setModel(modFormula);
         ListCem.setModel(modCem);
         Lista_c.setModel(moda_c);
         GetEHE ee=new GetEHE();
         for(int i=0;i<store.size();i++){
             ee=store.get(i);
              modGrupo.addElement(ee.getGrupo());
             modFormula.addElement(ee.gettodo());
             modCem.addElement(ee.getCm());
             moda_c.addElement(ee.geta_c());
                     
         }
    }

    private void checkGrupoIfOkey( Hashtable<Integer, List> MaxMinGrupos) {
        DefaultComboBoxModel mod=new  DefaultComboBoxModel();
        DefaultListModel modList=new  DefaultListModel();
        ComboGrupo.setModel(mod);
        ListGrupovalid.setModel(modList);
        boolean []max=new boolean[MaxMinGrupos.size()];
        boolean []min=new boolean[MaxMinGrupos.size()];
      
      
      
    
      for(int i=0;i<max.length;i++){
          mod.addElement("Grupo "+i);
            modList.addElement("Grupo "+i);
            max[i]=true;
             min[i]=true;
      }
      
      for(int i=0;i<MaxMinGrupos.size();i++){
          for(int j=0;j<store.size();j++){
             GetEHE e=store.get(j);
             double Maxcem=Double.parseDouble(MaxMinGrupos.get(i).getItem(0));
             double Mincem=Double.parseDouble(MaxMinGrupos.get(i).getItem(1));
             double Maxac=Double.parseDouble(MaxMinGrupos.get(i).getItem(2));
             double Minac=Double.parseDouble(MaxMinGrupos.get(i).getItem(3));
             
             if(e.getGrupo()==i&&!e.isOuctar()){
                 //System.out.println(i);
                 if(e.getCm()>Mincem+30||e.getCm()<Maxcem-30){
                 System.out.println("Is ouctar =  "+e.isOuctar());
                 max[i]=false;
                 e.setValidcm(false);
             }else{
                     e.setValidcm(true);
                 }
              if(e.geta_c()>Minac+0.04||e.geta_c()<Maxac-0.04){
                   min[i]=false;
                    e.setValidac(false);
                 }else{
                  e.setValidac(true);
              }
              store.put(j, e);
             }
            
             
             }
         
      }
             setGrupoVal(max,min);
             
            
          }
    
    public void setGrupoVal(boolean max[],boolean min[]){
                boolean f=true; 
        for(int i=0;i<max.length;i++){
            if(!min[i]||!max[i])
                f=false;
        switch(i){
                     case 0:
                         if(max[i]){
                             LCem0.setText("SI");
                             LCem0.setBackground(Color.green);
                          }
                         else
                         {
                           LCem0.setText("NO");
                             LCem0.setBackground(Color.RED);  
                         }
                         if(min[i]){
                             LCem8.setText("SI");
                             LCem8.setBackground(Color.green);
                          }
                         else
                         {
                           LCem8.setText("NO");
                             LCem8.setBackground(Color.RED);  
                         }
                             
                         
                         break;
                     case 1:
                          if(max[i]){
                             LCem1.setText("SI");
                             LCem1.setBackground(Color.green);
                          }
                         else
                         {
                           LCem1.setText("NO");
                             LCem1.setBackground(Color.RED);  
                         }
                         if(min[i]){
                             LCem9.setText("SI");
                             LCem9.setBackground(Color.green);
                          }
                         else
                         {
                           LCem9.setText("NO");
                             LCem9.setBackground(Color.RED);  
                         }
                         break;
                     case 2:
                          if(max[i]){
                             LCem2.setText("SI");
                             LCem2.setBackground(Color.green);
                          }
                         else
                         {
                           LCem2.setText("NO");
                             LCem2.setBackground(Color.RED);  
                         }
                         if(min[i]){
                             LCem10.setText("SI");
                             LCem10.setBackground(Color.green);
                          }
                         else
                         {
                           LCem10.setText("NO");
                             LCem10.setBackground(Color.RED);  
                         }
                         break;
                     case 3:
                         
                         if(max[i]){
                             LCem3.setText("SI");
                             LCem3.setBackground(Color.green);
                          }
                         else
                         {
                           LCem3.setText("NO");
                             LCem3.setBackground(Color.RED);  
                         }
                         if(min[i]){
                             LCem11.setText("SI");
                             LCem11.setBackground(Color.green);
                          }
                         else
                         {
                           LCem11.setText("NO");
                             LCem11.setBackground(Color.RED);  
                         }
                         break;
                     case 4:
                         if(max[i]){
                             LCem4.setText("SI");
                             LCem4.setBackground(Color.green);
                          }
                         else
                         {
                           LCem4.setText("NO");
                             LCem4.setBackground(Color.RED);  
                         }
                         if(min[i]){
                             LCem12.setText("SI");
                             LCem12.setBackground(Color.green);
                          }
                         else
                         {
                           LCem12.setText("NO");
                             LCem12.setBackground(Color.RED);  
                         }
                         
                         break;
                     case 5:
                         if(max[i]){
                             LCem5.setText("SI");
                             LCem5.setBackground(Color.green);
                          }
                         else
                         {
                           LCem5.setText("NO");
                             LCem5.setBackground(Color.RED);  
                         }
                         if(min[i]){
                             LCem13.setText("SI");
                             LCem13.setBackground(Color.green);
                          }
                         else
                         {
                           LCem13.setText("NO");
                             LCem13.setBackground(Color.RED);  
                         }
                         
                         break;
                     case 6:
                         if(max[i]){
                             LCem6.setText("SI");
                             LCem6.setBackground(Color.green);
                          }
                         else
                         {
                           LCem6.setText("NO");
                             LCem6.setBackground(Color.RED);  
                         }
                         if(min[i]){
                             LCem14.setText("SI");
                             LCem14.setBackground(Color.green);
                          }
                         else
                         {
                           LCem14.setText("NO");
                             LCem14.setBackground(Color.RED);  
                         }
                         
                         break;
                     case 7:
                         if(max[i]){
                             LCem7.setText("SI");
                             LCem7.setBackground(Color.green);
                          }
                         else
                         {
                           LCem7.setText("NO");
                             LCem7.setBackground(Color.RED);  
                         }
                         if(min[i]){
                             LCem15.setText("SI");
                             LCem15.setBackground(Color.green);
                          }
                         else
                         {
                           LCem15.setText("NO");
                             LCem15.setBackground(Color.RED);  
                         }
                         
                         break;
                     
                 }
     
        }
        if(f){
           Buttonfirmar.setEnabled(true);
           ButtonFirma2.setEnabled(true);
        }
        else{
             Buttonfirmar.setEnabled(false);
            //  ButtonFirma2.setEnabled(false);
        }
    }
    
    private void sacaFormulas(String Sql){
        database d=new database();
        try {
                store = d.GetAll(Sql);
                //d.getStore();
                 setDataToLists(store);
            } catch (SQLException ex) {
                Logger.getLogger(Alta.class.getName()).log(Level.SEVERE, null, ex);
            }
        try {
        // TODO add your handling code here:
         d=new database();
       MaxMinGrupos= d.getMax_Min_Grupo();
       
    } catch (SQLException ex) {
        Logger.getLogger(Alta.class.getName()).log(Level.SEVERE, null, ex);
    } 
        
        checkGrupoIfOkey(MaxMinGrupos);
    }

    private void formulaAlta() {
        
        GetEHE eHE=SolveformulaProblem();
       
         
        
         if(!TextCem.getText().equalsIgnoreCase("")&&!Textac.getText().equalsIgnoreCase("")) {   
         
        if(CompoEHE.getSelectedIndex()<3){
             database db=new database(eHE);
         if(Double.parseDouble(TextCem.getText())<db.getCemMax()||Double.parseDouble(Textac.getText())>db.getAcmin())
         {
             JOptionPane.showMessageDialog(null, "Error!!!! EL Cem Min ="+db.getCemMax()+" ,Y EL Max a/c = "+db.getAcmin());
             
         }else{
              
              BottonAddAmb3.setVisible(false);
              CompoAmbiente2.setVisible(false);
              CompoAmbiente3.setVisible(false);
               eHE.setResistencia(Integer.parseInt(CompoResistencia.getSelectedItem().toString()));
              eHE.setConsistencia(CompoConsistencia.getSelectedItem().toString());
              eHE.setTamanomax(Integer.parseInt(SpinnerTamanomax.getValue().toString()));
              eHE.setCm(Double.parseDouble(TextCem.getText()));
              eHE.seta_c(Double.parseDouble(Textac.getText()));
              TextAgua.setText(eHE.getAgua()+"");
              eHE.setGrupo(CompoResistencia.getSelectedIndex()+1);
              eHE.setCmmax(db.getCemMax());
              eHE.setAcmin(db.getAcmin());
              eHE.setIdPlanta(plantaID);
             
              
               boolean flag=true;
              for(int i=0;i<store.size();i++){
                 // System.out.println(store.get(i).gettodo()+"++++++++++++"+eHE.gettodo());
                  if(store.get(i).gettodo().equalsIgnoreCase(eHE.gettodo())){
                     flag=false;
                     //System.out.println(flag);
                     break;
                  }
                 
                      
              } 
              if(flag)
                 db.SaveDate(eHE);
              else{
                 String m="";
                   m = JOptionPane.showInputDialog("There is the same formula, add some comment to add it");
                         if(m==null)
                             JOptionPane.showMessageDialog(null, "same");
                           
                         else{
                             eHE.setDes(m);
                              db.SaveDate(eHE);
                         }
              }
              
         }
        }else{
        //if HL o HNL
       
        //if HL
        
        if(CompoEHE.getSelectedIndex()==3){
            System.out.println("//if HL");
           if(Double.parseDouble(TextCem.getText())<Double.parseDouble(CompoResistencia.getSelectedItem().toString())){
             JOptionPane.showMessageDialog(null, "Error!!!! EL Cem Min = "+CompoResistencia.getSelectedItem().toString());   
           } else{
              System.out.println();
              eHE.setIndicativoEHE08(CompoEHE.getSelectedItem().toString());
              eHE.setResistencia(Integer.parseInt(CompoResistencia.getSelectedItem().toString()));
              eHE.setConsistencia(CompoConsistencia.getSelectedItem().toString());
              eHE.setTamanomax(Integer.parseInt(SpinnerTamanomax.getValue().toString()));
              eHE.setCm(Double.parseDouble(TextCem.getText()));
              eHE.seta_c(Double.parseDouble(Textac.getText()));
              TextAgua.setText(eHE.getAgua()+"");
              eHE.setGrupo(0);
              eHE.setCmmax(Integer.parseInt(CompoResistencia.getSelectedItem().toString()));
              eHE.setAcmin(0);
               eHE.setIdPlanta(plantaID);
                boolean flag=true;
              for(int i=0;i<store.size();i++){
                 // System.out.println(store.get(i).gettodo()+"++++++++++++"+eHE.gettodo());
                  if(store.get(i).gettodo().equalsIgnoreCase(eHE.gettodo())){
                     flag=false;
                     //System.out.println(flag);
                     break;
                  }
                 
                      
              } 
              if(flag)
                 db.SaveDate(eHE);
              else{
                 String m="";
                   m = JOptionPane.showInputDialog("There is the same formula, add some coment to add it");
                         if(m==null)
                             JOptionPane.showMessageDialog(null, "same");
                           
                         else{
                             eHE.setDes(m);
                              db.SaveDate(eHE);
                         }
              }
           }
        }else{
              eHE.setIndicativoEHE08(CompoEHE.getSelectedItem().toString());
              eHE.setResistencia(Integer.parseInt(CompoResistencia.getSelectedItem().toString()));
              eHE.setConsistencia(CompoConsistencia.getSelectedItem().toString());
              eHE.setTamanomax(Integer.parseInt(SpinnerTamanomax.getValue().toString()));
              eHE.setCm(Double.parseDouble(TextCem.getText()));
              eHE.seta_c(Double.parseDouble(Textac.getText()));
              TextAgua.setText(eHE.getAgua()+"");
              eHE.setGrupo(0);
              eHE.setCmmax(0);
              eHE.setAcmin(0);
              eHE.setIdPlanta(plantaID);
                boolean flag=true;
              for(int i=0;i<store.size();i++){
                 // System.out.println(store.get(i).gettodo()+"++++++++++++"+eHE.gettodo());
                  if(store.get(i).gettodo().equalsIgnoreCase(eHE.gettodo())){
                     flag=false;
                     //System.out.println(flag);
                     break;
                  }
                 
                      
              } 
              if(flag)
                 db.SaveDate(eHE);
              else{
                 String m="";
                   m = JOptionPane.showInputDialog("There is the same formula, add some coment to add it");
                         if(m==null)
                             JOptionPane.showMessageDialog(null, "same");
                           
                         else{
                             eHE.setDes(m);
                              db.SaveDate(eHE);
                         }
              }
              
        }
           
    }
        
                      
              
              
              
                  
        
        
        
         database d=new database();
        try {
                 store =d.GetAll("");
                
                 setDataToLists(store);
            } catch (SQLException ex) {
                Logger.getLogger(Alta.class.getName()).log(Level.SEVERE, null, ex);
            } 
         sacaFormulas("");
         }else{
            JOptionPane.showMessageDialog(null, "Pon Cem y a/c"); 
         }
    }

    private GetEHE SolveformulaProblem() {
        GetEHE eHE=new GetEHE();
     
        if(CompoEHE.getSelectedIndex()<3){
       eHE.setIndicativoEHE08(CompoEHE.getSelectedItem().toString());
       eHE.setAmbiente1(CompoAmbiente1.getSelectedItem().toString());
      // System.out.println(eHE.getAmbiente1()+"     "+eHE.getIndicativoEHE08());
        
        if(CompoAmbiente2.isVisible())
        {
             eHE.setAmbiente2(CompoAmbiente2.getSelectedItem().toString());
            if(CompoAmbiente3.isVisible())
            {
                 eHE.setAmbiente3(CompoAmbiente3.getSelectedItem().toString());
                 if(CompoAmbiente4.isVisible())
            {
                 eHE.setAmbiente4(CompoAmbiente4.getSelectedItem().toString());
            }
            }
        }
        }
        
        return eHE;
    }

    
      }
    
              
    

    


